fetching workflow run id

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -63,4 +63,20 @@ jobs:
                   -d '{"ref":"PETOSS-536-enabling-workflow-dispatch","inputs":{"branch_name": "${{github.head_ref}}"}}')
                 echo "Triggered workflow with response:"
                 echo $response
-            
+
+            - name: Get workflow run ID
+              id: get-run-id
+              run: |
+                run_id=$(curl -s \
+                  -H 'Authorization: Bearer ${{ steps.get_access_token.outputs.result }}' \
+                  -H "Accept: application/vnd.github.everest-preview+json" \
+                  -H "X-GitHub-Api-Version: 2022-11-28" \
+                  https://api.github.com/repos/xero-internal/xeroapi-sdk-codegen/actions/runs \
+                  | jq -r '.workflow_runs[] | select(.head_branch=="PETOSS-536-enabling-workflow-dispatch") | .id' | head -n 1)
+
+                if [ -z "$run_id"]; then
+                  echo "Failed to retrieve workflow run id"
+                  exit 1
+                else
+                 echo "workflow run ID: $run_id"
+                fi
